# Generated by Django 2.2 on 2020-12-14 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0002_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
