# Generated by Django 2.2 on 2020-12-14 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0004_auto_20201213_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quoted_by',
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quote_by_user', to='quote_app.User'),
            preserve_default=False,
        ),
    ]
